package kr.or.connect.reservation.dao.sqls;

public class ProductDaoSqls {
	public static final String SELECT_BY_CATEGORY = ""
		+ "SELECT "
		+ "		content			AS product_content, \n"
		+ "		description 	AS product_description, \n"
		+ "		product.id 		AS product_id, \n"
		+ "		display.id 		AS display_info_id, \n"
		+ "		place_name, \n"
		+ "		file.save_file_name AS product_image_url \n"
		+ "FROM "
		+ "		product \n"
		+ "JOIN "
		+ "		display_info AS display "
		+ "ON "
		+ "		product.id = display.product_id \n"
		+ "JOIN "
		+ "		product_image AS image "
		+ "ON "
		+ "		product.id = image.product_id \n"
		+ "JOIN "
		+ "		file_info AS file "
		+ "ON "
		+ "		image.file_id = file.id \n"
		+ "WHERE "
		+ "		product.category_id = :categoryid \n"
		+ "AND "
		+ "		image.type =\"th\" \n"
		+ "ORDER BY "
		+ "		display_info_id DESC \n"
		+ "limit :start, :limit";

	public static final String SELECT_ALL = ""
		+ "SELECT "
		+ "		content 			AS product_content, \n"
		+ "		description			AS product_description, \n"
		+ "		product.id 			AS product_id, \n"
		+ "		display.id 			AS display_info_id, \n"
		+ "		place_name, \n"
		+ "		file.save_file_name AS product_image_url \n"
		+ "FROM "
		+ "		product \n"
		+ "JOIN "
		+ "		display_info AS display "
		+ "ON "
		+ "		product.id = display.product_id \n"
		+ "JOIN "
		+ "		product_image AS image "
		+ "ON "
		+ "		product.id = image.product_id \n"
		+ "JOIN "
		+ "		file_info AS file "
		+ "ON "
		+ "		image.file_id = file.id \n"
		+ "AND "
		+ "		image.type =\"th\" \n"
		+ "ORDER BY "
		+ "		display_info_id DESC \n"
		+ "limit :start, :limit";

	public static final String SELECT_COUNT_BY_CATEGORY = ""
		+ "SELECT "
		+ "		COUNT(*) "
		+ "FROM "
		+ "		product \n"
		+ "JOIN "
		+ "		display_info \n"
		+ "ON "
		+ "		(product.id = display_info.product_id) \n"
		+ "WHERE "
		+ "		category_id = :categoryid";

	public static final String SELECT_COUNT_ALL = ""
		+ "SELECT "
		+ "		COUNT(*) "
		+ "FROM "
		+ "		product \n"
		+ "JOIN "
		+ "		display_info \n"
		+ "ON "
		+ "		(product.id = display_info.product_id)";

	public static final String SELECT_IMAGES_BY_ID = ""
		+ "SELECT "
		+ "		file.content_type	AS content_type, "
		+ "     file.create_date 	AS create_date, "
		+ "     file.delete_flag 	AS delete_flag, "
		+ "     file.id 			AS file_info_id, "
		+ "     file.file_name		AS file_name, "
		+ "     file.modify_date	AS modify_date, "
		+ "     file.save_file_name AS save_file_name, \n"

		+ "    	image.product_id	AS product_id, "
		+ "    	image.id 			AS product_image_id, "
		+ "    	image.type 			AS type \n"
		+ "FROM "
		+ "		product_image AS image \n"
		+ "JOIN "
		+ "		file_info AS file \n"
		+ "ON "
		+ "		image.file_id = file.id \n"
		+ "WHERE "
		+ "		product_id = :id \n"
		+ "AND "
		+ "		type != \"th\";";

	public static final String SELECT_PRICES_BY_ID = ""
		+ "SELECT "
		+ "		create_date, "
		+ "		discount_rate, "
		+ "     modify_date, "
		+ "     price, "
		+ "		price_type_name, "
		+ "	    product_id, "
		+ "    	id AS product_price_id \n"
		+ "FROM "
		+ "		product_price \n"
		+ "WHERE "
		+ "		product_id = :id;";

}
